'''
Pentagon Numbers
Problem #44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''

#pn = [(3*n-1)*n//2 for n in range(1, 10000)]
##print(pn)
#for n, i in zip(pn, range(10000)):
#    for nn in pn[i:]:
#        if nn - n in pn and nn + n in pn:
#            print(n)

#Solutions

import math

def isPentagonal(x):
    r = math.sqrt(1 + 24 * x)
    return r % 6 == 5

def solution():
    for j in range(1,5000):
        Pj = j * (3 * j - 1) / 2
        for k in range(j+1, 5000):
            Pk = k * (3 * k - 1) / 2
            if isPentagonal(Pk - Pj) and isPentagonal(Pj + Pk):
                print(Pk - Pj)
solution()
