'''
Triangular, pentabonal, and hexagonal
Problem #45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

from tqdm import trange
import sys

#found = False
#LIMIT = 10000
#tn = pn = hn = 40755
##tn = pn = hn = 1
##for h, hi in zip(range(5,LIMIT,4), range(1,LIMIT)):
#for h in trange(4*143-3,LIMIT//3,4):
#    hn = hn + h
##    print('hn', hn)
#    pn = 40755
##    for p, pi in zip(range(4,LIMIT,3), range(1,LIMIT)):
#    for p, pi in zip(range(4*165-2,LIMIT//2,3), range(1,LIMIT)):
#        pn =  pn + p
##        print('pn', pn)
#        tn = 40755
##        for t in range(2,LIMIT,1):
#        for t in range(285,LIMIT,1):
#            tn = tn + t
##            if tn == 40755:
##                print(hn, pn, tn)
#            if tn == pn and tn == hn:
#                found = True
#                print('found!')
#                print(t, pi+1)
#                print(tn)
#                break
#    if found:
#        break

# Solutions

import math
import time

def isPentagonal(x):
    r = math.sqrt(1 + 24 * x)
    return r % 6 == 5

def solution():
    m = 144
    while True:
        res = 2 * m * m - m
        if isPentagonal(res):
            return res
        m += 1
    return False

start = time.time()
print(solution())
end = time.time() - start
print(end)
